"""your message

Revision ID: 0a6f43dfb112
Revises: 9786a51a0dd1
Create Date: 2026-01-18 10:49:24.172017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6f43dfb112'
down_revision = '9786a51a0dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
